/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */
 

#include "rpcMiner.h"
#include <string.h>

#define MAX_DESAFIOS 400

struct elements {
	int transactionID;
	int challenge;
	int clientID;
	char seed[40];
};
typedef struct elements elements;

int tamanhoLista = 0;
elements listaDesafios[MAX_DESAFIOS];

int *
gettransactionid_100_svc(void *argp, struct svc_req *rqstp)
{
	static int  result;
	printf("tamanholista = %d\n", tamanhoLista);
	if (tamanhoLista == 0){
		elements e;
		e.transactionID = 0;
		e.clientID = -1;
		e.challenge = 1;
		listaDesafios[tamanhoLista] = e;
		result = tamanhoLista;
		tamanhoLista++;
		return &result;
	}
	if (listaDesafios[tamanhoLista-1].clientID != -1){
		elements e;
		e.transactionID = tamanhoLista+1;
		e.clientID = -1;
		e.challenge = (tamanhoLista % 128) + 1;
		listaDesafios[tamanhoLista] = e;
		result = tamanhoLista;
		tamanhoLista++;
		return &result;
	}
	result = tamanhoLista-1;
	return &result;
}

int *
getchallenge_100_svc(int *argp, struct svc_req *rqstp)
{
	static int  result;
	int transactionID = *argp;
	if (tamanhoLista == 0){
		elements e;
		e.transactionID = 0;
		e.clientID = -1;
		e.challenge = 1;
		listaDesafios[tamanhoLista] = e;
		result = e.challenge;
		tamanhoLista++;
	}
	if (transactionID >= tamanhoLista){
		result = -1;
		return &result;
	}
	result = listaDesafios[transactionID].challenge;

	return &result;
}

int *
gettransactionstatus_100_svc(int *argp, struct svc_req *rqstp)
{
	static int  result;

	int transactionID = *argp;
	if (tamanhoLista == 0){
		elements e;
		e.transactionID = 0;
		e.clientID = -1;
		e.challenge = 1;
		listaDesafios[tamanhoLista] = e;
		tamanhoLista++;
	}
	if (transactionID >= tamanhoLista){
		result = -1;
		return &result;
	}
	result = listaDesafios[transactionID].clientID == -1 ? 1: 0;
	return &result;
}

int *
submitchallenge_100_svc(challengeTuple *argp, struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */

	return &result;
}

int *
getwinner_100_svc(int *argp, struct svc_req *rqstp)
{
	static int  result;

	int transactionID = *argp;
	if (tamanhoLista == 0){
		elements e;
		e.transactionID = 0;
		e.clientID = -1;
		e.challenge = 1;
		listaDesafios[tamanhoLista] = e;
		tamanhoLista++;
	}
	if (transactionID >= tamanhoLista){
		result = -1;
		return &result;
	}
	int w = listaDesafios[transactionID].clientID;
	result = w == -1 ? 0: w;

	return &result;
}

row *
getseed_100_svc(int *argp, struct svc_req *rqstp)
{
	static row  result;

	int transactionID = *argp;
	if (tamanhoLista == 0){
		elements e;
		e.transactionID = 0;
		e.clientID = -1;
		e.challenge = 1;
		listaDesafios[tamanhoLista] = e;
		tamanhoLista++;
	}
	if (transactionID >= tamanhoLista){
		result = -1;
		return &result;
	}
	result.status = listaDesafios[transactionID].clientID == -1 ? 1: 0;
	result.desafio = listaDesafios[transactionID].challenge;
	

	return &result;
}
